In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
import torchvision
import torchvision.transforms as transforms

In [3]:
import numpy as np

# 01. Basic Autograd_01

In [19]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [20]:
y = w * x + b

In [21]:
y.backward()

In [22]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


# 2. Basic Autoggrad_02

In [23]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)
linear = nn.Linear(3, 2)

In [24]:
criterion = nn.MSELoss()
optimizer = optim.SGD(linear.parameters(), lr=0.01)

In [25]:
for loop in range(1, 10):
    pred = linear(x)
    loss = criterion(pred, y)
    if loop % 2 == 0:
        print("Loss: {}".format(loss.item()))
    loss.backward()
    optimizer.step()

Loss: 1.936963677406311
Loss: 1.7079187631607056
Loss: 1.3662046194076538
Loss: 1.0104750394821167


# 3. Loading data from numpy

In [26]:
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)
z = y.numpy()

In [27]:
print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


# 4. Input pipline

In [51]:
train_dataset = torchvision.datasets.CIFAR10(
    root="../../dataset/CIFAR10/", train=True,
    transform=transforms.ToTensor(), download=True)

Files already downloaded and verified


In [29]:
image, label = train_dataset[0]
print(image.size())
print(label)

torch.Size([3, 32, 32])
6


In [30]:
train_loader = torch.utils.data.DataLoader(
    dataset=train_dataset, batch_size=64,
    shuffle=True)

In [31]:
data_iter = iter(train_loader)
images, labels = data_iter.next()

In [32]:
for images, labels in train_loader:
   # Here's the training code
   pass

# 5. Custom Dataset Loader

In [33]:
class CustomDataset(torch.utils.data.DataLoader):
    def __init__(self):
        # TODO
        # Initialize file paths or sth. like a list
        pass

    def __getitem__(self, index):
        # TODO
        # 1. Read from file (e.g. using np.fromfile, PIL.Image.open)
        # 2. Preprocess the data (e.g. using torchvision.Transform)
        # 3. Return a data pair => (image, label)
        pass

    def __len__(self):
        # Based on the dataset
        return 0

In [34]:
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
                                           batch_size=64,
                                           shuffle=True)

# 6. Pretrained Model

In [37]:
resnet = torchvision.models.resnet18(pretrained=True)

In [39]:
# if just want to finetune the top layer of the net:
for param in resnet.parameters():
    param.requires_grad = False

# e.g. : replace the top layer:
resnet.fc = nn.Linear(resnet.fc.in_features, 100) # JUST FOR EXAMPLE

In [40]:
image = torch.randn(64, 3, 224, 224)

In [41]:
outputs = resnet(image)

In [44]:
outputs.size()

torch.Size([64, 100])

# 7. Save the model

In [45]:
# 01. save the entire model
torch.save(resnet, "model.ckpt")

In [46]:
model = torch.load("model.ckpt")

In [49]:
# 02. save only the paramaters (MOST RECOMMANDED!!!)
torch.save(resnet.state_dict(), "param.ckpt")

In [50]:
resnet.load_state_dict(torch.load("param.ckpt"))